#!/bin/sh
 
echo "Running pre-commit checks..."
 
# Block .env files
if git diff --cached --name-only | grep -E '\.env$'; then
  echo "ERROR: .env file detected. Remove it before commit."
  exit 1
fi
 
# Block .log files
if git diff --cached --name-only | grep -E '\.log$'; then
  echo "ERROR: .log file detected. Remove it before commit."
  exit 1
fi
 
# JS formatting check
npx prettier --check "Week1/DAY5/**/*.js"
 
if [ $? -ne 0 ]; then
  echo "ERROR: JavaScript files are not formatted."
  exit 1
fi
 
echo "Pre-commit checks passed"
